// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serverTracking.proto

package ServerTracking;

public final class ServerTrackingServiceImpl {
  private ServerTrackingServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServerIDRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ServerIDRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServerInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ServerInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServerLocationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ServerLocationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServerLocationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ServerLocationRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024serverTracking.proto\"#\n\017ServerIDReques" +
      "t\022\020\n\010serverID\030\001 \001(\t\"[\n\022ServerInfoRespons" +
      "e\022\020\n\010serverID\030\001 \001(\t\022\020\n\010location\030\002 \001(\t\022\016\n" +
      "\006status\030\003 \001(\t\022\021\n\ttimestamp\030\004 \001(\003\"O\n\026Serv" +
      "erLocationResponse\022\020\n\010serverID\030\001 \001(\t\022\020\n\010" +
      "location\030\002 \001(\t\022\021\n\ttimestamp\030\003 \001(\003\">\n\025Ser" +
      "verLocationRequest\022\020\n\010serverID\030\001 \001(\t\022\023\n\013" +
      "newLocation\030\002 \001(\t2\334\001\n\025ServerTrackingServ" +
      "ice\0226\n\013trackServer\022\020.ServerIDRequest\032\023.S" +
      "erverInfoResponse\"\000\022@\n\021getServerLocation" +
      "\022\020.ServerIDRequest\032\027.ServerLocationRespo" +
      "nse\"\000\022I\n\024updateServerLocation\022\026.ServerLo" +
      "cationRequest\032\027.ServerLocationResponse\"\000" +
      "B-\n\016ServerTrackingB\031ServerTrackingServic" +
      "eImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ServerIDRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ServerIDRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ServerIDRequest_descriptor,
        new java.lang.String[] { "ServerID", });
    internal_static_ServerInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ServerInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ServerInfoResponse_descriptor,
        new java.lang.String[] { "ServerID", "Location", "Status", "Timestamp", });
    internal_static_ServerLocationResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ServerLocationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ServerLocationResponse_descriptor,
        new java.lang.String[] { "ServerID", "Location", "Timestamp", });
    internal_static_ServerLocationRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ServerLocationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ServerLocationRequest_descriptor,
        new java.lang.String[] { "ServerID", "NewLocation", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
