// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serverTracking.proto

package ServerTracking;

public interface ServerLocationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ServerLocationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string serverID = 1;</code>
   */
  java.lang.String getServerID();
  /**
   * <code>string serverID = 1;</code>
   */
  com.google.protobuf.ByteString
      getServerIDBytes();

  /**
   * <code>string newLocation = 2;</code>
   */
  java.lang.String getNewLocation();
  /**
   * <code>string newLocation = 2;</code>
   */
  com.google.protobuf.ByteString
      getNewLocationBytes();
}
