// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serverTracking.proto

package ServerTracking;

public interface ServerLocationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ServerLocationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string serverID = 1;</code>
   */
  java.lang.String getServerID();
  /**
   * <code>string serverID = 1;</code>
   */
  com.google.protobuf.ByteString
      getServerIDBytes();

  /**
   * <code>string location = 2;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 2;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>int64 timestamp = 3;</code>
   */
  long getTimestamp();
}
