// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serverTracking.proto

package ServerTracking;

public interface ServerInfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ServerInfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string serverID = 1;</code>
   */
  java.lang.String getServerID();
  /**
   * <code>string serverID = 1;</code>
   */
  com.google.protobuf.ByteString
      getServerIDBytes();

  /**
   * <code>string location = 2;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 2;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>string status = 3;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 3;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>int64 timestamp = 4;</code>
   */
  long getTimestamp();
}
