// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serverTracking.proto

package ServerTracking;

public interface ServerIDRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ServerIDRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *wrap input parameters
   * </pre>
   *
   * <code>string serverID = 1;</code>
   */
  java.lang.String getServerID();
  /**
   * <pre>
   *wrap input parameters
   * </pre>
   *
   * <code>string serverID = 1;</code>
   */
  com.google.protobuf.ByteString
      getServerIDBytes();
}
