// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: facialRecognition.proto

package FacialRecognition;

public final class FacialRecognitionServiceImpl {
  private FacialRecognitionServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RecognitionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RecognitionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Face_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Face_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PersonRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PersonRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PersonIDRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PersonIDRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027facialRecognition.proto\"\035\n\014ImageReques" +
      "t\022\r\n\005image\030\001 \001(\014\"K\n\023RecognitionResponse\022" +
      "\036\n\017recognizedFaces\030\001 \003(\0132\005.Face\022\024\n\014error" +
      "Message\030\002 \001(\t\"\'\n\004Face\022\020\n\010personID\030\001 \001(\t\022" +
      "\r\n\005image\030\002 \001(\014\"C\n\rPersonRequest\022\020\n\010perso" +
      "nID\030\001 \001(\t\022\r\n\005image\030\002 \001(\014\022\021\n\ttimestamp\030\003 " +
      "\001(\003\"#\n\017PersonIDRequest\022\020\n\010personID\030\001 \001(\t" +
      "\"\007\n\005Empty2\247\001\n\030FacialRecognitionService\0228" +
      "\n\rrecogniseFace\022\r.ImageRequest\032\024.Recogni" +
      "tionResponse\"\000(\001\022%\n\taddPerson\022\016.PersonRe" +
      "quest\032\006.Empty\"\000\022*\n\014deletePerson\022\020.Person" +
      "IDRequest\032\006.Empty\"\000B3\n\021FacialRecognition" +
      "B\034FacialRecognitionServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ImageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ImageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImageRequest_descriptor,
        new java.lang.String[] { "Image", });
    internal_static_RecognitionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RecognitionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RecognitionResponse_descriptor,
        new java.lang.String[] { "RecognizedFaces", "ErrorMessage", });
    internal_static_Face_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Face_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Face_descriptor,
        new java.lang.String[] { "PersonID", "Image", });
    internal_static_PersonRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_PersonRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PersonRequest_descriptor,
        new java.lang.String[] { "PersonID", "Image", "Timestamp", });
    internal_static_PersonIDRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_PersonIDRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PersonIDRequest_descriptor,
        new java.lang.String[] { "PersonID", });
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
