// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: facialRecognition.proto

package FacialRecognition;

public interface ImageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ImageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes image = 1;</code>
   */
  com.google.protobuf.ByteString getImage();
}
