// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: facialRecognition.proto

package FacialRecognition;

public interface PersonIDRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PersonIDRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string personID = 1;</code>
   */
  java.lang.String getPersonID();
  /**
   * <code>string personID = 1;</code>
   */
  com.google.protobuf.ByteString
      getPersonIDBytes();
}
