// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: facialRecognition.proto

package FacialRecognition;

public interface RecognitionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RecognitionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Face recognizedFaces = 1;</code>
   */
  java.util.List<FacialRecognition.Face> 
      getRecognizedFacesList();
  /**
   * <code>repeated .Face recognizedFaces = 1;</code>
   */
  FacialRecognition.Face getRecognizedFaces(int index);
  /**
   * <code>repeated .Face recognizedFaces = 1;</code>
   */
  int getRecognizedFacesCount();
  /**
   * <code>repeated .Face recognizedFaces = 1;</code>
   */
  java.util.List<? extends FacialRecognition.FaceOrBuilder> 
      getRecognizedFacesOrBuilderList();
  /**
   * <code>repeated .Face recognizedFaces = 1;</code>
   */
  FacialRecognition.FaceOrBuilder getRecognizedFacesOrBuilder(
      int index);

  /**
   * <code>string errorMessage = 2;</code>
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string errorMessage = 2;</code>
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();
}
