// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: facialRecognition.proto

package FacialRecognition;

/**
 * Protobuf type {@code RecognitionResponse}
 */
public  final class RecognitionResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:RecognitionResponse)
    RecognitionResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RecognitionResponse.newBuilder() to construct.
  private RecognitionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RecognitionResponse() {
    recognizedFaces_ = java.util.Collections.emptyList();
    errorMessage_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RecognitionResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              recognizedFaces_ = new java.util.ArrayList<FacialRecognition.Face>();
              mutable_bitField0_ |= 0x00000001;
            }
            recognizedFaces_.add(
                input.readMessage(FacialRecognition.Face.parser(), extensionRegistry));
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            errorMessage_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        recognizedFaces_ = java.util.Collections.unmodifiableList(recognizedFaces_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return FacialRecognition.FacialRecognitionServiceImpl.internal_static_RecognitionResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return FacialRecognition.FacialRecognitionServiceImpl.internal_static_RecognitionResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            FacialRecognition.RecognitionResponse.class, FacialRecognition.RecognitionResponse.Builder.class);
  }

  private int bitField0_;
  public static final int RECOGNIZEDFACES_FIELD_NUMBER = 1;
  private java.util.List<FacialRecognition.Face> recognizedFaces_;
  /**
   * <code>repeated .Face recognizedFaces = 1;</code>
   */
  public java.util.List<FacialRecognition.Face> getRecognizedFacesList() {
    return recognizedFaces_;
  }
  /**
   * <code>repeated .Face recognizedFaces = 1;</code>
   */
  public java.util.List<? extends FacialRecognition.FaceOrBuilder> 
      getRecognizedFacesOrBuilderList() {
    return recognizedFaces_;
  }
  /**
   * <code>repeated .Face recognizedFaces = 1;</code>
   */
  public int getRecognizedFacesCount() {
    return recognizedFaces_.size();
  }
  /**
   * <code>repeated .Face recognizedFaces = 1;</code>
   */
  public FacialRecognition.Face getRecognizedFaces(int index) {
    return recognizedFaces_.get(index);
  }
  /**
   * <code>repeated .Face recognizedFaces = 1;</code>
   */
  public FacialRecognition.FaceOrBuilder getRecognizedFacesOrBuilder(
      int index) {
    return recognizedFaces_.get(index);
  }

  public static final int ERRORMESSAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object errorMessage_;
  /**
   * <code>string errorMessage = 2;</code>
   */
  public java.lang.String getErrorMessage() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      errorMessage_ = s;
      return s;
    }
  }
  /**
   * <code>string errorMessage = 2;</code>
   */
  public com.google.protobuf.ByteString
      getErrorMessageBytes() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errorMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < recognizedFaces_.size(); i++) {
      output.writeMessage(1, recognizedFaces_.get(i));
    }
    if (!getErrorMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errorMessage_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < recognizedFaces_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, recognizedFaces_.get(i));
    }
    if (!getErrorMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, errorMessage_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof FacialRecognition.RecognitionResponse)) {
      return super.equals(obj);
    }
    FacialRecognition.RecognitionResponse other = (FacialRecognition.RecognitionResponse) obj;

    boolean result = true;
    result = result && getRecognizedFacesList()
        .equals(other.getRecognizedFacesList());
    result = result && getErrorMessage()
        .equals(other.getErrorMessage());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRecognizedFacesCount() > 0) {
      hash = (37 * hash) + RECOGNIZEDFACES_FIELD_NUMBER;
      hash = (53 * hash) + getRecognizedFacesList().hashCode();
    }
    hash = (37 * hash) + ERRORMESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getErrorMessage().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static FacialRecognition.RecognitionResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static FacialRecognition.RecognitionResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static FacialRecognition.RecognitionResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static FacialRecognition.RecognitionResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static FacialRecognition.RecognitionResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static FacialRecognition.RecognitionResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static FacialRecognition.RecognitionResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static FacialRecognition.RecognitionResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static FacialRecognition.RecognitionResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static FacialRecognition.RecognitionResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static FacialRecognition.RecognitionResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static FacialRecognition.RecognitionResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(FacialRecognition.RecognitionResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RecognitionResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RecognitionResponse)
      FacialRecognition.RecognitionResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FacialRecognition.FacialRecognitionServiceImpl.internal_static_RecognitionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FacialRecognition.FacialRecognitionServiceImpl.internal_static_RecognitionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FacialRecognition.RecognitionResponse.class, FacialRecognition.RecognitionResponse.Builder.class);
    }

    // Construct using FacialRecognition.RecognitionResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRecognizedFacesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (recognizedFacesBuilder_ == null) {
        recognizedFaces_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        recognizedFacesBuilder_.clear();
      }
      errorMessage_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return FacialRecognition.FacialRecognitionServiceImpl.internal_static_RecognitionResponse_descriptor;
    }

    @java.lang.Override
    public FacialRecognition.RecognitionResponse getDefaultInstanceForType() {
      return FacialRecognition.RecognitionResponse.getDefaultInstance();
    }

    @java.lang.Override
    public FacialRecognition.RecognitionResponse build() {
      FacialRecognition.RecognitionResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public FacialRecognition.RecognitionResponse buildPartial() {
      FacialRecognition.RecognitionResponse result = new FacialRecognition.RecognitionResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (recognizedFacesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          recognizedFaces_ = java.util.Collections.unmodifiableList(recognizedFaces_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.recognizedFaces_ = recognizedFaces_;
      } else {
        result.recognizedFaces_ = recognizedFacesBuilder_.build();
      }
      result.errorMessage_ = errorMessage_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof FacialRecognition.RecognitionResponse) {
        return mergeFrom((FacialRecognition.RecognitionResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(FacialRecognition.RecognitionResponse other) {
      if (other == FacialRecognition.RecognitionResponse.getDefaultInstance()) return this;
      if (recognizedFacesBuilder_ == null) {
        if (!other.recognizedFaces_.isEmpty()) {
          if (recognizedFaces_.isEmpty()) {
            recognizedFaces_ = other.recognizedFaces_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRecognizedFacesIsMutable();
            recognizedFaces_.addAll(other.recognizedFaces_);
          }
          onChanged();
        }
      } else {
        if (!other.recognizedFaces_.isEmpty()) {
          if (recognizedFacesBuilder_.isEmpty()) {
            recognizedFacesBuilder_.dispose();
            recognizedFacesBuilder_ = null;
            recognizedFaces_ = other.recognizedFaces_;
            bitField0_ = (bitField0_ & ~0x00000001);
            recognizedFacesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRecognizedFacesFieldBuilder() : null;
          } else {
            recognizedFacesBuilder_.addAllMessages(other.recognizedFaces_);
          }
        }
      }
      if (!other.getErrorMessage().isEmpty()) {
        errorMessage_ = other.errorMessage_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      FacialRecognition.RecognitionResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (FacialRecognition.RecognitionResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<FacialRecognition.Face> recognizedFaces_ =
      java.util.Collections.emptyList();
    private void ensureRecognizedFacesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        recognizedFaces_ = new java.util.ArrayList<FacialRecognition.Face>(recognizedFaces_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        FacialRecognition.Face, FacialRecognition.Face.Builder, FacialRecognition.FaceOrBuilder> recognizedFacesBuilder_;

    /**
     * <code>repeated .Face recognizedFaces = 1;</code>
     */
    public java.util.List<FacialRecognition.Face> getRecognizedFacesList() {
      if (recognizedFacesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(recognizedFaces_);
      } else {
        return recognizedFacesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Face recognizedFaces = 1;</code>
     */
    public int getRecognizedFacesCount() {
      if (recognizedFacesBuilder_ == null) {
        return recognizedFaces_.size();
      } else {
        return recognizedFacesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Face recognizedFaces = 1;</code>
     */
    public FacialRecognition.Face getRecognizedFaces(int index) {
      if (recognizedFacesBuilder_ == null) {
        return recognizedFaces_.get(index);
      } else {
        return recognizedFacesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Face recognizedFaces = 1;</code>
     */
    public Builder setRecognizedFaces(
        int index, FacialRecognition.Face value) {
      if (recognizedFacesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecognizedFacesIsMutable();
        recognizedFaces_.set(index, value);
        onChanged();
      } else {
        recognizedFacesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Face recognizedFaces = 1;</code>
     */
    public Builder setRecognizedFaces(
        int index, FacialRecognition.Face.Builder builderForValue) {
      if (recognizedFacesBuilder_ == null) {
        ensureRecognizedFacesIsMutable();
        recognizedFaces_.set(index, builderForValue.build());
        onChanged();
      } else {
        recognizedFacesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Face recognizedFaces = 1;</code>
     */
    public Builder addRecognizedFaces(FacialRecognition.Face value) {
      if (recognizedFacesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecognizedFacesIsMutable();
        recognizedFaces_.add(value);
        onChanged();
      } else {
        recognizedFacesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Face recognizedFaces = 1;</code>
     */
    public Builder addRecognizedFaces(
        int index, FacialRecognition.Face value) {
      if (recognizedFacesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecognizedFacesIsMutable();
        recognizedFaces_.add(index, value);
        onChanged();
      } else {
        recognizedFacesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Face recognizedFaces = 1;</code>
     */
    public Builder addRecognizedFaces(
        FacialRecognition.Face.Builder builderForValue) {
      if (recognizedFacesBuilder_ == null) {
        ensureRecognizedFacesIsMutable();
        recognizedFaces_.add(builderForValue.build());
        onChanged();
      } else {
        recognizedFacesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Face recognizedFaces = 1;</code>
     */
    public Builder addRecognizedFaces(
        int index, FacialRecognition.Face.Builder builderForValue) {
      if (recognizedFacesBuilder_ == null) {
        ensureRecognizedFacesIsMutable();
        recognizedFaces_.add(index, builderForValue.build());
        onChanged();
      } else {
        recognizedFacesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Face recognizedFaces = 1;</code>
     */
    public Builder addAllRecognizedFaces(
        java.lang.Iterable<? extends FacialRecognition.Face> values) {
      if (recognizedFacesBuilder_ == null) {
        ensureRecognizedFacesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, recognizedFaces_);
        onChanged();
      } else {
        recognizedFacesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Face recognizedFaces = 1;</code>
     */
    public Builder clearRecognizedFaces() {
      if (recognizedFacesBuilder_ == null) {
        recognizedFaces_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        recognizedFacesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Face recognizedFaces = 1;</code>
     */
    public Builder removeRecognizedFaces(int index) {
      if (recognizedFacesBuilder_ == null) {
        ensureRecognizedFacesIsMutable();
        recognizedFaces_.remove(index);
        onChanged();
      } else {
        recognizedFacesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Face recognizedFaces = 1;</code>
     */
    public FacialRecognition.Face.Builder getRecognizedFacesBuilder(
        int index) {
      return getRecognizedFacesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Face recognizedFaces = 1;</code>
     */
    public FacialRecognition.FaceOrBuilder getRecognizedFacesOrBuilder(
        int index) {
      if (recognizedFacesBuilder_ == null) {
        return recognizedFaces_.get(index);  } else {
        return recognizedFacesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Face recognizedFaces = 1;</code>
     */
    public java.util.List<? extends FacialRecognition.FaceOrBuilder> 
         getRecognizedFacesOrBuilderList() {
      if (recognizedFacesBuilder_ != null) {
        return recognizedFacesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(recognizedFaces_);
      }
    }
    /**
     * <code>repeated .Face recognizedFaces = 1;</code>
     */
    public FacialRecognition.Face.Builder addRecognizedFacesBuilder() {
      return getRecognizedFacesFieldBuilder().addBuilder(
          FacialRecognition.Face.getDefaultInstance());
    }
    /**
     * <code>repeated .Face recognizedFaces = 1;</code>
     */
    public FacialRecognition.Face.Builder addRecognizedFacesBuilder(
        int index) {
      return getRecognizedFacesFieldBuilder().addBuilder(
          index, FacialRecognition.Face.getDefaultInstance());
    }
    /**
     * <code>repeated .Face recognizedFaces = 1;</code>
     */
    public java.util.List<FacialRecognition.Face.Builder> 
         getRecognizedFacesBuilderList() {
      return getRecognizedFacesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        FacialRecognition.Face, FacialRecognition.Face.Builder, FacialRecognition.FaceOrBuilder> 
        getRecognizedFacesFieldBuilder() {
      if (recognizedFacesBuilder_ == null) {
        recognizedFacesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            FacialRecognition.Face, FacialRecognition.Face.Builder, FacialRecognition.FaceOrBuilder>(
                recognizedFaces_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        recognizedFaces_ = null;
      }
      return recognizedFacesBuilder_;
    }

    private java.lang.Object errorMessage_ = "";
    /**
     * <code>string errorMessage = 2;</code>
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string errorMessage = 2;</code>
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string errorMessage = 2;</code>
     */
    public Builder setErrorMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      errorMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string errorMessage = 2;</code>
     */
    public Builder clearErrorMessage() {
      
      errorMessage_ = getDefaultInstance().getErrorMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string errorMessage = 2;</code>
     */
    public Builder setErrorMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      errorMessage_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:RecognitionResponse)
  }

  // @@protoc_insertion_point(class_scope:RecognitionResponse)
  private static final FacialRecognition.RecognitionResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new FacialRecognition.RecognitionResponse();
  }

  public static FacialRecognition.RecognitionResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RecognitionResponse>
      PARSER = new com.google.protobuf.AbstractParser<RecognitionResponse>() {
    @java.lang.Override
    public RecognitionResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RecognitionResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RecognitionResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RecognitionResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public FacialRecognition.RecognitionResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

