// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: boundaryAnomoly.proto

package BoundaryAnomolyDetection;

public interface AnomalyIDRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AnomalyIDRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string anomalyID = 1;</code>
   */
  java.lang.String getAnomalyID();
  /**
   * <code>string anomalyID = 1;</code>
   */
  com.google.protobuf.ByteString
      getAnomalyIDBytes();
}
