// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: boundaryAnomoly.proto

package BoundaryAnomolyDetection;

public interface AnomalyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AnomalyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string anomalyID = 1;</code>
   */
  java.lang.String getAnomalyID();
  /**
   * <code>string anomalyID = 1;</code>
   */
  com.google.protobuf.ByteString
      getAnomalyIDBytes();

  /**
   * <code>bytes image = 2;</code>
   */
  com.google.protobuf.ByteString getImage();

  /**
   * <code>int64 timestamp = 3;</code>
   */
  long getTimestamp();
}
