// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: boundaryAnomoly.proto

package BoundaryAnomolyDetection;

public interface AuditTrailResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AuditTrailResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string anomalyID = 1;</code>
   */
  java.lang.String getAnomalyID();
  /**
   * <code>string anomalyID = 1;</code>
   */
  com.google.protobuf.ByteString
      getAnomalyIDBytes();

  /**
   * <code>bool anomalyFlag = 2;</code>
   */
  boolean getAnomalyFlag();

  /**
   * <code>int64 timestamp = 3;</code>
   */
  long getTimestamp();

  /**
   * <code>string personID = 4;</code>
   */
  java.lang.String getPersonID();
  /**
   * <code>string personID = 4;</code>
   */
  com.google.protobuf.ByteString
      getPersonIDBytes();
}
