// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: boundaryAnomoly.proto

package BoundaryAnomolyDetection;

public final class BADServiceImpl {
  private BADServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BoundaryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BoundaryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AnomalyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AnomalyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AnomalyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AnomalyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AnomalyIDRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AnomalyIDRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AuditTrailResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AuditTrailResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OverrideRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OverrideRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025boundaryAnomoly.proto\";\n\017BoundaryReque" +
      "st\022\022\n\nboundaryID\030\001 \001(\t\022\024\n\014boundaryZone\030\002" +
      " \001(\t\"E\n\016AnomalyRequest\022\021\n\tanomalyID\030\001 \001(" +
      "\t\022\r\n\005image\030\002 \001(\014\022\021\n\ttimestamp\030\003 \001(\003\"L\n\017A" +
      "nomalyResponse\022\021\n\tanomalyID\030\001 \001(\t\022\023\n\013ano" +
      "malyFlag\030\002 \001(\010\022\021\n\ttimestamp\030\003 \001(\003\"%\n\020Ano" +
      "malyIDRequest\022\021\n\tanomalyID\030\001 \001(\t\"a\n\022Audi" +
      "tTrailResponse\022\021\n\tanomalyID\030\001 \001(\t\022\023\n\013ano" +
      "malyFlag\030\002 \001(\010\022\021\n\ttimestamp\030\003 \001(\003\022\020\n\010per" +
      "sonID\030\004 \001(\t\"v\n\017OverrideRequest\022\021\n\tanomal" +
      "yID\030\001 \001(\t\022\022\n\nreasonCode\030\002 \001(\005\022\027\n\017reasonE" +
      "xplained\030\003 \001(\t\022\021\n\ttimestamp\030\004 \001(\003\022\020\n\010per" +
      "sonID\030\005 \001(\t\"\007\n\005Empty2\374\001\n\026BoundaryAnomaly" +
      "Service\022)\n\013setBoundary\022\020.BoundaryRequest" +
      "\032\006.Empty\"\000\022@\n\025detectBoundaryAnomaly\022\017.An" +
      "omalyRequest\032\020.AnomalyResponse\"\000(\0010\001\022B\n\024" +
      "getAnomalyAuditTrail\022\021.AnomalyIDRequest\032" +
      "\023.AuditTrailResponse\"\0000\001\0221\n\023overrideAler" +
      "tStatus\022\020.OverrideRequest\032\006.Empty\"\000B,\n\030B" +
      "oundaryAnomolyDetectionB\016BADServiceImplP" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_BoundaryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BoundaryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BoundaryRequest_descriptor,
        new java.lang.String[] { "BoundaryID", "BoundaryZone", });
    internal_static_AnomalyRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AnomalyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AnomalyRequest_descriptor,
        new java.lang.String[] { "AnomalyID", "Image", "Timestamp", });
    internal_static_AnomalyResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_AnomalyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AnomalyResponse_descriptor,
        new java.lang.String[] { "AnomalyID", "AnomalyFlag", "Timestamp", });
    internal_static_AnomalyIDRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_AnomalyIDRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AnomalyIDRequest_descriptor,
        new java.lang.String[] { "AnomalyID", });
    internal_static_AuditTrailResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_AuditTrailResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AuditTrailResponse_descriptor,
        new java.lang.String[] { "AnomalyID", "AnomalyFlag", "Timestamp", "PersonID", });
    internal_static_OverrideRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_OverrideRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OverrideRequest_descriptor,
        new java.lang.String[] { "AnomalyID", "ReasonCode", "ReasonExplained", "Timestamp", "PersonID", });
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
