// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: boundaryAnomoly.proto

package BoundaryAnomolyDetection;

public interface BoundaryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BoundaryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string boundaryID = 1;</code>
   */
  java.lang.String getBoundaryID();
  /**
   * <code>string boundaryID = 1;</code>
   */
  com.google.protobuf.ByteString
      getBoundaryIDBytes();

  /**
   * <code>string boundaryZone = 2;</code>
   */
  java.lang.String getBoundaryZone();
  /**
   * <code>string boundaryZone = 2;</code>
   */
  com.google.protobuf.ByteString
      getBoundaryZoneBytes();
}
