// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: boundaryAnomoly.proto

package BoundaryAnomolyDetection;

public interface OverrideRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OverrideRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string anomalyID = 1;</code>
   */
  java.lang.String getAnomalyID();
  /**
   * <code>string anomalyID = 1;</code>
   */
  com.google.protobuf.ByteString
      getAnomalyIDBytes();

  /**
   * <code>int32 reasonCode = 2;</code>
   */
  int getReasonCode();

  /**
   * <code>string reasonExplained = 3;</code>
   */
  java.lang.String getReasonExplained();
  /**
   * <code>string reasonExplained = 3;</code>
   */
  com.google.protobuf.ByteString
      getReasonExplainedBytes();

  /**
   * <code>int64 timestamp = 4;</code>
   */
  long getTimestamp();

  /**
   * <code>string personID = 5;</code>
   */
  java.lang.String getPersonID();
  /**
   * <code>string personID = 5;</code>
   */
  com.google.protobuf.ByteString
      getPersonIDBytes();
}
